[align.0-tel_coarse]  # coarse alignment using cluster correlation
method = "correlations"
sensor_ids = [0,1,2,3,4,5]
align_ids = [1,2,3,4,5]  # keep first plane fixed
estimate_beam_parameters = true

[align.1-tel_coarse_inner]  # coarse alignment for inner planes
method = "correlations"
sensor_ids = [0,1,2,3,4,5]
align_ids = [1,2,3,4]  # keep first and last plane fixed
estimate_beam_parameters = true

[align.2-tel_fine_chi]
method = "localchi2"
sensor_ids = [0,1,2,3,4,5]
align_ids =    [1,2,3,4]        # keep first and last plane fixed
num_steps = 30                  # number of iterative alignment steps
search_spatial_sigma_max = 20.0  # distance search window for track finding
reduced_chi2_max = 5.0         # chi2 cut for track finding
estimate_beam_parameters = true

[align.3-dut_coarse]
method = "correlations" 
sensor_ids = [0,1,2,3,4,5,6,7,8]
align_ids = [6,7,8]
estimate_beam_parameters = false

[align.4-dut_fine]
method = "residuals" # correlations, residuals
sensor_ids = [0,1,2,3,4,5,6,7,8]
align_ids = [6,7,8]
num_steps = 10
search_spatial_sigma_max = 5.0
reduced_chi2_max = 10.0
estimate_beam_parameters = false

#[align.5-dut_fine_chi2]
#method = "localchi2"
#sensor_ids = [0,1,2,3,4,5]
#align_ids =    [1,2,3,4]  # keep first and last plane fixed
#num_steps = 10
#search_spatial_sigma_max = 5.0
#reduced_chi2_max = 10.0
