[beam]
# in GeV
energy = 120.0
slope = [0.0, 0.0]
divergence = [0.001, 0.001]


# zpos: [-120, -100, -80, 305, 325, 345]
# DUT 80 + [10, 30, 50]
# in mm
[[sensors]]
id = 0
offset = [0.0, 0.0, 0.0]
unit_u = [1.0, 0.0, 0.0]
unit_v = [0.0, 1.0, 0.0]

[[sensors]] 
id = 1
offset = [0.0, 0.0,  20.0]
unit_u = [1.0, 0.0,   0.0]
unit_v = [0.0, 1.0,   0.0]

[[sensors]]
id = 2
offset = [0.0, 0.0,  40.0]
unit_u = [1.0, 0.0,   0.0]
unit_v = [0.0, 1.0,   0.0]

[[sensors]]
id = 3
offset = [0.0, 0.0, 425.0]
unit_u = [1.0, 0.0,   0.0]
unit_v = [0.0, 1.0,   0.0]

[[sensors]]
id = 4
offset = [0.0, 0.0, 445.0]
unit_u = [1.0, 0.0,   0.0]
unit_v = [0.0, 1.0,   0.0]

[[sensors]]
id = 5
offset = [0.0, 0.0, 465.0]
unit_u = [1.0, 0.0,   0.0]
unit_v = [0.0, 1.0,   0.0]

[[sensors]]
id = 6
offset = [0.0, 0.0, 380.0]
unit_u = [1.0, 0.0,   0.0]
unit_v = [0.0, 1.0,   0.0]

[[sensors]]
id = 7
offset = [0.0, 0.0, 130.0]
unit_u = [0.0, 1.0,   0.0]
unit_v = [1.0, 0.0,   0.0]

[[sensors]]
id = 8
offset = [0.0, 0.0, 150.0]
unit_u = [0.0, 1.0,   0.0]
unit_v = [1.0, 0.0,   0.0]

[[sensors]]
id = 9
offset = [0.0, 0.0, 170.0]
unit_u = [0.0, 1.0,   0.0]
unit_v = [1.0, 0.0,   0.0]

